### PR TITLE
Add ruff configuration + CI workflow

### PR DESCRIPTION
**Pull request by cc-a**
This PR setups up the repository to use ruff and adds a CI workflow that runs for pull requests.

Currently only one rule is enabled [F821](https://docs.astral.sh/ruff/rules/undefined-name/). This finds undefined names in the code base mostly missing imports but also the odd typo. I've fixed all of the violations that were trivial but there remain a few that need a more expert eye. Plesae feel free to amend this PR with the fixes.

It's worth noting that the full set of [F rules](https://docs.astral.sh/ruff/rules/#pyflakes-f) catches 182 violations but 162 of these can be automatically fixed by ruff. Besides the outstanding F821 violations the remaining things to fix would all be unused imports or unused variables. Both pretty easy to take care of. Worth considering I think to reasonable rule coverage with fairly low effort.

### CODE REVIEW

**Comment by cc-a** [comment]
Ah the workflow runs will need to be approved as this PR is coming from a fork.

**Comment by plasorak** [comment]
Thanks Chris.

Everything works as expected, I'm just going to request that `ruff` be added into the python venv before we merge this, since it's now in `setup.py`.

**Comment by cc-a** [comment]
Done

**Review by plasorak — APPROVED** [review]
Very nice, thanks!

**Pull request merged**
