### PR TITLE
Titavare/host

### PR DESCRIPTION
**Pull request by PawelPlesniak**
Adding the hostname to `ps`

### CODE REVIEW

**Comment by TiagoTAlves** [comment]
image

**Comment by TiagoTAlves** [comment]
Addresses Issue #129

**Comment by TiagoTAlves** [comment]
Requires https://github.com/DUNE-DAQ/druncschema/pull/19 to work

**Review by alessandrothea — APPROVED** [review]
See comments in https://github.com/DUNE-DAQ/druncschema/pull/19

**Pull request merged**
